#
# docker build -t spark-client -f Dockerfile-spark-client .
#
FROM spark-base:latest

ENV PROJECT_HOME=/proj

RUN mkdir ${PROJECT_HOME}
WORKDIR ${PROJECT_HOME}

COPY spark-client.py client.py

CMD ${SPARK_HOME}/bin/spark-submit --packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.4.3 ${PROJECT_HOME}/client.py