#
# docker build -t spark-master -f Dockerfile-spark-master .
#
FROM spark-base:latest

# ENV
ENV SPARK_MASTER_PORT=7077
ENV SPARK_MASTER_WEBUI_PORT=8080
ENV SPARK_MASTER_HOST=spark-master

ENV SPARK_WORKER_CORES=1
ENV SPARK_WORKER_MEMORY=1g

EXPOSE 7077 8080

# 启动
CMD /spark/$SPARK_VERSION/bin/spark-class org.apache.spark.deploy.master.Master --ip $SPARK_MASTER_HOST --port $SPARK_MASTER_PORT --webui-port $SPARK_MASTER_WEBUI_PORT