#
# docker build -t java-base -f Dockerfile-java-base .
#
FROM ubuntu:xenial

COPY ./common/sources.list /etc/apt/sources.list
RUN apt-get update --fix-missing -y && apt-get update -y

# JAVA环境
RUN apt-get install -y openjdk-8-jdk \ 
			apt-transport-https 

# ENV
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
