#
# docker build -t spark-client -f Dockerfile-spark-client .
#
FROM spark-base:latest

ENV PROJECT_HOME=/proj

RUN mkdir ${PROJECT_HOME}
WORKDIR ${PROJECT_HOME}

COPY spark-client.py client.py

CMD python3 ${PROJECT_HOME}/client.py